"""add access_url to digital_assets

Revision ID: cadc974eac25
Revises: 20260515_0006
Create Date: 2026-05-17 14:01:56.289609
"""

from alembic import op
import sqlalchemy as sa



revision = 'cadc974eac25'
down_revision = '20260515_0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_assets', sa.Column('access_url', sa.String(length=2000), nullable=True))
    op.add_column('digital_assets', sa.Column('access_url_expires_at', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_digital_assets_title'), 'digital_assets', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digital_assets_title'), table_name='digital_assets')
    op.drop_column('digital_assets', 'access_url_expires_at')
    op.drop_column('digital_assets', 'access_url')
    # ### end Alembic commands ###
